### ISSUE TITLE
No documentation for the change of dev.minn.jda.ktx.interactions.command

### ISSUE THREAD

**Issue by bananasmoothii** [MinnDevelopment/jda-ktx#27]
Hello, I was forced to updated (tanks jitpack...), and I spent a lot of time finding out that `dev.minn.jda.ktx.interactions.command` has been replaced by `dev.minn.jda.ktx.interactions.slash` (to register slash commands).
It may be a good idea to document that change or better, make it deprecated before removing it...
Thanks!

**Comment by MinnDevelopment** [comment]
Alpha builds receive breaking changes on updates regularly. I will not be documenting them, you can follow the commits to see what changed. I highly recommend to specific exact commit hashes as version instead of snapshots.

**Comment by bananasmoothii** [comment]
Oh, I understand. But how do I make the difference between alpha builds and stable builds ?
