### ISSUE TITLE
Upgrade to Kotlin 1.6.20

### ISSUE THREAD

**Issue by TheOnlyTails** [MinnDevelopment/jda-ktx#28]
Kotlin 1.6.20 is now out, and I'd love to use it for my bot.

**Comment by MinnDevelopment** [comment]
What's stopping you from using it? It should be entirely compatible with this library.

**Comment by TheOnlyTails** [comment]
Ah, I saw in the README that it requires Kotlin 1.6.10, so I assumed it required a specific version as well.
