### ISSUE TITLE
Inline Message Builder / Embed Builder

### ISSUE THREAD

**Issue by Arthur-IO** [MinnDevelopment/jda-ktx#29]
I don't know if I'm using the correct implementation, but when I use this code the embeds always come out as being empty and gives the error message can't be built without content.

Dependencies are the exact same versions as the ones listed on the READ_ME

I am also getting this error within my editor when trying to use the code sample in the READ_ME:
[Error Image](https://i.gyazo.com/c98ca3f6fe067c0acae5706920dead65.png)

The code I tried
`
val message = Message {

    embeds += Embed {
        title = "Hespori Reaction Roles"
        description = """
            React below to select which Hespori Seeds you'd like to be notified about.
                        
            You'll be assigned a Discord Role for each reaction, and be tagged whenever your selected seeds are planted
            
            :one: = Attas (Bonus XP)
            :two: = Kronos (x2 Raids)
            :three: = Iasor (x2 Drops)
            :four: = Golpar (x2 Crystal Keys, Clues, etc.)
            :five: = Noxifer (x2 Slayer points)
            :six: = Buchu (x2 Boss Points)
            :seven: = Celastrus (x2 Brimstone keys)
            :eight: = Consecration (+5 PC Points)
            :nine: = Kelda (x2 Larran's keys)
        """.trimIndent()
        }
}`

**Comment by MinnDevelopment** [comment]
It looks like you accidentally imported things unrelated to the builders. `SendDefault.components` is not something you want here.

**Comment by Arthur-IO** [comment]
Thank you for the prompt reply.

Oddly enough I am not able to see `embeds` or `components` within the InlineMessage context 

[Error](https://i.gyazo.com/56d813ef69f5348fe1989570ec8aa2b8.png)

**Comment by MinnDevelopment** [comment]
You have to use the latest master commit.

**Comment by Arthur-IO** [comment]
Sorry for the trouble, after Invalidating the caches then refreshing my Gradle project the context was received.

Thank you again, Happy Holidays. Hope you have a great day :D
