### ISSUE TITLE
throwing this error ClassCastException 

### ISSUE THREAD

**Issue by OMAR-3OOV** [MinnDevelopment/jda-ktx#36]
I'm trying to use jda#button() { //code } to make things way easier and don't need to use the event for the button but once the called this method I get an error I literally didn't understand it, maybe it's a bug for something?

**Error ( ClassCastException  ) :**
`
class net.dv8tion.jda.api.hooks.InterfacedEventManager cannot be cast to class dev.minn.jda.ktx.events.CoroutineEventManager (net.dv8tion.jda.api.hooks.InterfacedEventManager and dev.minn.jda.ktx.events.CoroutineEventManager are in unnamed module of loader 'app')
`

**The way how i use them:** 
![image](https://user-images.githubusercontent.com/50619134/175868650-083e3732-e9c4-46d9-9e3f-744a954b663a.png)

**Comment by OMAR-3OOV** [comment]
btw the error comes from the first one.

**Comment by MinnDevelopment** [comment]
Using `jda.button` requires setting up the coroutine event manager.

**Comment by OMAR-3OOV** [comment]
can you tell me about this please? i can't find any  source in google about it

**Comment by MinnDevelopment** [comment]
Check the [readme example](https://github.com/MinnDevelopment/jda-ktx#examples)

**Comment by OMAR-3OOV** [comment]
> Check the [readme example](https://github.com/MinnDevelopment/jda-ktx#examples)

Oh thanks, it's work, but another thing is when I try to call for example `event.guild.getMemberById(id)` It throws an error which is **NullPointer**, I'm already enabled the `MemberCache` in the setup, and **GatewayIntent.GUILD_MEMBERS**, I tried this as well, `event.guild.memerCache.getElementById(id)` still not work
