### ISSUE TITLE
IllegalStateException project cannot starting

### ISSUE THREAD

**Issue by OMAR-3OOV** [MinnDevelopment/jda-ktx#40]
Recently JDA added new intent **MESSAGE_CONTENT**, anyway I added it and the project started giving IllegalStateException error, it says that I have to add awaitStatus, I don't actually know exactly what should I use so I tried all of them and none of them work so idk if it's a bug or I have missed something! ( I'm using the last version )

My code : 
- intents
```kotlin
val gateways = arrayListOf(
                GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_MEMBERS,
                GatewayIntent.GUILD_MESSAGE_REACTIONS, GatewayIntent.GUILD_MESSAGES,
                GatewayIntent.GUILD_MESSAGE_TYPING, GatewayIntent.GUILD_PRESENCES,
                GatewayIntent.DIRECT_MESSAGES, GatewayIntent.DIRECT_MESSAGE_REACTIONS
            )
```
- build :
```kotlin
val jda = light(token, enableCoroutines = true, intents = gateways) {
                enableCache(
                    CacheFlag.ACTIVITY,
                    CacheFlag.ONLINE_STATUS,
                    CacheFlag.ROLE_TAGS,
                    CacheFlag.MEMBER_OVERRIDES,
                )
                disableCache(EnumSet.of(CacheFlag.EMOJI, CacheFlag.VOICE_STATE))
                setMemberCachePolicy(MemberCachePolicy.ALL)
                setChunkingFilter(ChunkingFilter.ALL)
                addEventListeners(Events(Main), RPCEvent(), MessengerEvent())
            }.awaitReady()
```
- Error : 
```cmd
Exception in thread "main" java.lang.IllegalStateException: Was shutdown trying to await status
	at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:496)
	at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:324)
	at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:374)
	at Main$Companion.start(Main.kt:48)
	at MainKt.main(Main.kt:77)
	at MainKt.main(Main.kt)
```

**Comment by MinnDevelopment** [comment]
That exception tells you there was another exception which caused the shutdown before. Make sure your logger is setup correctly to print out the log messages of JDA. You most likely did not enable the intent in your [application dashboard](https://discord.com/developers/applications) and are getting [this error](https://jda.wiki/using-jda/troubleshooting/#im-getting-closecode4014-disallowed-intents).

**Comment by OMAR-3OOV** [comment]
I'm sure everything is right, and everything is enabled also this issue only appears when I use `GatewayIntent.MESSAGE_CONTENT` also the message I get is `WebSocket connection was closed and cannot be recovered due to i`

**Comment by MinnDevelopment** [comment]
Then you got exactly the [error i linked just now](https://jda.wiki/using-jda/troubleshooting/#im-getting-closecode4014-disallowed-intents) and should follow the instruction.
