### ISSUE TITLE
Builders not working right

### ISSUE THREAD

**Issue by CoasterFreakDE** [MinnDevelopment/jda-ktx#6]
**Specs**:
Kotlin: 1.5.0
JDK: 16
JVMTarget: 13
OS: Windows 10
JDA: 4.2.1_253
JDA-KTX: 0.3.1

---

**Bug**:
When using the EmbedBuilder from Builders.kt some fields are ignored.

What I found:
- footer not working at all
- timestamp never showing up
- Message(content, embed) working but Message { content = content, embed { ... }} not working at all
- description of Embed { } not working

**Steps to reproduce**:

Just use the example Embed from the README.md

```kt
        val embed = Embed {
            title = "Hello Friend"
            description = "Goodbye Friend"
            field {
                name = "How good is this example?"
                value = "5 :star:"
                inline = false
            }
            timestamp = Instant.now()
            color = 0xFF0000
        }
```

Renders to: 
![image](https://user-images.githubusercontent.com/28011628/121493274-f75ab280-c9d7-11eb-8dd5-2dd0227693ac.png)

Should be:
![image](https://user-images.githubusercontent.com/28011628/121493213-e3af4c00-c9d7-11eb-8221-20c865db79e0.png)

**Comment by CoasterFreakDE** [comment]
When using 

```kt
val embed = Embed(title="Hello Friend", description="Goodbye Friend", timestamp = Instant.now(), footerText = "Test", footerIcon = MOD_MANAGER_CREDIT_ICON)
```

the embed renders just fine.

![image](https://user-images.githubusercontent.com/28011628/121493905-89fb5180-c9d8-11eb-9ff5-97ccbf8ccf2b.png)

**Comment by MinnDevelopment** [comment]
Fixed in https://github.com/MinnDevelopment/jda-ktx/commit/1a45395155b30d1b323c19469ab49de32704c2cc

**Comment by RyanMalaspina** [comment]
Hello, I'm running into this issue with embeds for `Message { ... }` vs `Message(...)` in ea0a1b2

```kotlin
// Embed is not in message
Message {
    content = /* */
    embed = /* */
}

// Embed is in message
Message(
    content = /* */,
    embed = /* */
)
```

JDA 4.3.0_299
Kotlin 1.5.21
JVM 15
